/**
 * User: Ian
 * Date: 01/03/14
 * Time: 7:15 PM
 * Project: AVObj vs 0.4 - Making JS Simple.
 * Copyright (c) 2014 Ian Carson - LinkedIn http://lnkd.in/9qJWap
 * License : MIT (http://www.opensource.org/licenses/mit-license.php)
 */
"use strict"
Function.prototype.bind||(Function.prototype.bind=function(e){if("function"!=typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable")
	var t=Array.prototype.slice.call(arguments,1),r=this,n=function(){},o=function(){return r.apply(this instanceof n?this:e||window,t.concat(Array.prototype.slice.call(arguments)))}
	return n.prototype=this.prototype,o.prototype=new n,o})
var AVObj={init:function(){},deInit:function(){},create:function(){var e=this.createFinal()
	return e.init.apply(e,arguments),e},extend:function(e){var t=this.createObject()
	return e&&(e.generateSingleton&&(t.create=function(){console.error("Please use singleton constructor 'instance' instead.")},t.instance=function(){return null==t._instance&&(t._instance=this.createFinal(),this.init.apply(t._instance,arguments)),t._instance}),e.initOnPageLoad&&AVObj._AVLoadList.push(t),e.initStaticObject&&(t.create=function(){console.error("Cannot create a static object!")},t.destroy=function(){console.error("Cannot destroy a static object!")}),e.preventExtension&&(t._lockExtensions=!0)),t},destroy:function(){this.deInit()},createFinal:function(){return Object.create(this,{parent:{get:function(){return console.error("Cannot get from keyword 'this.parent'. Please avoid any parent calls that could be scoped to other objects!"),null},enumerable:!1,configurable:!1},"super":{value:function(){return console.error("Cannot call super(); with 'this.super'. please avoid any super calls that could be scoped to other objects!"),null},writable:!1,configurable:!1},_observers:{value:{},writable:!1,configurable:!1,enumerable:!1}})},createObject:function(){return Object.create(this,{parent:{get:function(){return Object.getPrototypeOf(this)},enumerable:!1,configurable:!1},"super":{value:function(){return Object.getPrototypeOf(this).init.apply(this,arguments)},writable:!1,configurable:!1},_observers:{value:{},writable:!1,configurable:!1,enumerable:!1}})},set properties(e){"object"==typeof e.advanced&&Object.defineProperties(this,e)
	for(var t in e)"object"!=typeof e[t]||null==e[t]||"function"!=typeof e[t].get&&"function"!=typeof e[t].set?this[t]=e[t]:Object.defineProperty(this,t,e[t])
	this._lockExtensions&&Object.preventExtensions(this)},attachObserverModel:function(e){e._observers||e.setObserverScope||(Object.defineProperties(e,{_observers:{value:{},writable:!1}}),e.setObserverScope=AVObj.setObserverScope,e.fireObservers=AVObj.fireObservers,e.addObserver=AVObj.addObserver,e.removeObserver=AVObj.removeObserver)},fireObservers:function(e,t){if(this._observers[e])for(var r=this._observers[e].scope.length;r--;)this._observers[e].scope[r](t)},addObserver:function(e,t,r){r||(r=window),this._observers[e]||(this._observers[e]={scope:[],original:[]}),this._observers[e]?r[t]?(this._observers[e].scope.push(r[t].bind(r)),this._observers[e].original.push(r[t])):console.error(t+" Does not exist in the given scope of ",r):console.error(e+" : Scope does not exists or has not yet been set.")},getNumObservers:function(e){return this._observers[e]?this._observers[e].scope.length:0},removeObserver:function(e,t,r){var n=this._observers[e].original.indexOf(r[t])
	n>=0&&(this._observers[e].scope=this._observers[e].scope.splice(n,1),this._observers[e].original=this._observers[e].original.splice(n,1))},removeObservers:function(e){this._observers[e]={scope:[],original:[]}}}
Object.defineProperties(AVObj,{_observers:{value:{},writable:!1,configurable:!1,enumerable:!1},_AVLoadList:{value:[],writable:!1,configurable:!1,enumerable:!1},parent:{value:AVObj}}),window.addEventListener("load",function(){AVObj._AVLoadList.forEach(function(e){null==e._instance?(e._instance=e.createFinal(),e._instance.init()):console.warn("Object "+e+" has already been created.")})})