/**
 * User: Ian
 * Date: 01/03/14
 * Time: 7:15 PM
 * Project: AVObj vs 0.01 - Making JS Simple.
 * Copyright (c) 2014 Ian Carson - LinkedIn http://lnkd.in/9qJWap
 * License : MIT (http://www.opensource.org/licenses/mit-license.php)
 */
'use strict';Function.prototype.bind||(Function.prototype.bind=function(a){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var b=Array.prototype.slice.call(arguments,1),c=this,d=function(){},e=function(){return c.apply(this instanceof d?this:a||window,b.concat(Array.prototype.slice.call(arguments)))};d.prototype=this.prototype;e.prototype=new d;return e});
var AVObj={init:function(){},deInit:function(){},create:function(){var a=this.createFinal();a.init.apply(a,arguments);return a},extend:function(){return this.createObject()},instance:function(){null==this._instance&&(this._instance=this.createFinal(),this.init.apply(this._instance,arguments));return this._instance},destroy:function(){this.deInit()},empty:function(){for(var a=arguments.length;a--;)if(!arguments[a]||0===arguments[a].length)return!0;return!1},addClean:function(a,b){return a.parentNode.element(a.nodeName,
	b)},element:function(a,b){var c=document.createElement(a),d;for(d in b)switch(d){case "text":c.addText(b[d]);break;default:c.setAttribute(d,b[d])}return c},createFinal:function(){return Object.create(this,{parent:{get:function(){console.error("Cannot get from keyword 'this.parent'. Please avoid any parent calls that could be scoped to other objects!");return null},enumerable:!1,configurable:!1},super:{value:function(){console.error("Cannot call super(); with 'this.super'. please avoid any super calls that could be scoped to other objects!");
	return null},writable:!1,configurable:!1},_observers:{value:{},writable:!1,configurable:!1,enumerable:!1}})},createObject:function(){return Object.create(this,{parent:{get:function(){return Object.getPrototypeOf(this)},enumerable:!1,configurable:!1},super:{value:function(){return Object.getPrototypeOf(this).init.apply(this,arguments)},writable:!1,configurable:!1},_observers:{value:{},writable:!1,configurable:!1,enumerable:!1}})},set properties(a){for(var b in a)"object"==typeof a[b]&&null!=a[b]&&
	(a[b].get||a[b].set)?Object.defineProperty(this,b,a[b]):this[b]=a[b]},set advProperties(a){Object.defineProperties(this,a)},preventExtensions:function(){Object.preventExtensions(this)},attachObserverModel:function(a){a._observers||a.setObserverScope||(Object.defineProperties(a,{_observers:{value:{},writable:!1}}),a.setObserverScope=AVObj.setObserverScope,a.fireObservers=AVObj.fireObservers,a.addObserver=AVObj.addObserver,a.removeObserver=AVObj.removeObserver)},fireObservers:function(a,b){if(this._observers[a])for(var c=
	this._observers[a].scope.length;c--;)this._observers[a].scope[c](b)},addObserver:function(a,b,c){this._observers[a]||(this._observers[a]={scope:[],original:[]});this._observers[a]?c[b]?(this._observers[a].scope.push(c[b].bind(c)),this._observers[a].original.push(c[b])):console.error(b+" Does not exist in the given scope of ",c):console.error(a+" : Scope does not exists or has not yet been set.")},removeObserver:function(a,b,c){b=this._observers[a].original.indexOf(c[b]);0<=b&&(this._observers[a].scope=
	this._observers[a].scope.splice(b,1),this._observers[a].original=this._observers[a].original.splice(b,1))}};Object.defineProperties(AVObj,{_observers:{value:{},writable:!1,configurable:!1,enumerable:!1},parent:{value:AVObj}});